# Spring Boot properties
spring.application.name=SwissCouponBooster
spring.main.web-application-type=servlet
spring.threads.virtual.enabled=true

# Support reading from .env file during development
spring.config.import=optional:file:../.env[.properties],optional:file:.env[.properties]

# Logging
logging.level.org.apache.hc.client5.http.wire=DEBUG

# Application Config
swiss.coupon.booster.headless-enabled=false
swiss.coupon.booster.debug-cookies=false

# Migros Cumulus
migros.cumulus.enabled=true
migros.account.username=${MIGROS_ACCOUNT_USERNAME}
migros.account.password=${MIGROS_ACCOUNT_PASSWORD}
migros.account.login-url=https://login.migros.ch/login
migros.cumulus.login-url=https://www.migros.ch/de/cumulus/konto~checkImmediate=true~.html
migros.cumulus.coupons-url=https://account.migros.ch/ma/api/user/cumulus/coupon
migros.cumulus.coupons-activation-url=https://account.migros.ch/ma/api/user/cumulus/coupon/activation

# Coop Supercard
coop.supercard.enabled=true
coop.supercard.start-url=https://www.supercard.ch/
coop.supercard.username=${COOP_SUPERCARD_USERNAME}
coop.supercard.password=${COOP_SUPERCARD_PASSWORD}
coop.supercard.login-url=https://login.supercard.ch/cas/login?service=https://www.supercard.ch/

# DataDome Cookie is valid for up-to 1 year
# e.g. Set-Cookie: datadome=1UoW~hVN8RqeEw5Fvr56...; Max-Age=31536000; Domain=.supercard.ch;
coop.supercard.datadome-cookie=${COOP_SUPERCARD_DATADOME_COOKIE_VALUE}

coop.supercard.digital-bons-url=https://www.supercard.ch/content/supercard/de/supercard-digital/digitale-bons.html

coop.supercard.config-url=https://www.supercard.ch/bin/coop/supercard/oidc/pwa/configs.json
coop.supercard.config-url-referer=https://www.supercard.ch/de/app-digitale-services/digitale-bons.html

coop.supercard.coupons-url=https://webapi.supercard.ch/digital-coupons/api/v1/protected/dc?pageSize=9999&language=de
coop.supercard.coupons-deactivation-url=https://webapi.supercard.ch/digital-coupons/api/v1/protected/dc/action/deactivate?language=de
coop.supercard.coupons-activation-url=https://webapi.supercard.ch/digital-coupons/api/v1/protected/dc/action/activate?language=de

# JobRunr
org.jobrunr.background-job-server.enabled=true
org.jobrunr.dashboard.enabled=true

# Enables JobRunr with Spring Actuator Metrics - Only enable it on your server that has the dashboard running
org.jobrunr.jobs.metrics.enabled=true

# Spring Boot Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# SBOM endpoints
management.endpoint.sbom.additional.jvm.location=optional:file:/layers/sbom/launch/paketo-buildpacks_bellsoft-liberica/jre/sbom.syft.json
management.endpoint.sbom.additional.executable-jar.location=optional:file:/layers/sbom/launch/paketo-buildpacks_executable-jar/sbom.syft.json
management.endpoint.sbom.additional.spring-boot.location=optional:file:/layers/sbom/launch/paketo-buildpacks_spring-boot/spring-cloud-bindings/sbom.syft.json
management.endpoint.sbom.additional.launcher.location=optional:file:/layers/sbom/launch/buildpacksio_lifecycle/launcher/sbom.syft.json
# Merged version of all SBOMs in legacy Paketo format
management.endpoint.sbom.additional.legacy.location=optional:file:/layers/sbom/launch/sbom.legacy.json